export type SkillCategory =
  | 'Standard Typing'
  | 'Names'
  | 'Addresses'
  | 'Phone Numbers'
  | 'Emails'
  | 'Dates'
  | 'Invoice Numbers'
  | 'Order Numbers'
  | 'Customer IDs'
  | 'Account Numbers'
  | 'SKUs / Product Codes'
  | 'Tracking Numbers'
  | 'Dollar Amounts'
  | '10-Key Number Pad'
  | 'Customer Notes'
  | 'Office Forms'
  | 'Mixed Data Entry'
  | 'Weak Skill Practice';
