import { Link } from 'react-router-dom'
export default function Terms() {
  return (
    <div className="page" style={{maxWidth:700}}>
      <h1 className="page-title">Terms of Service</h1>
      <div className="card card-lg" style={{lineHeight:1.8}}>
        <p className="text-muted text-sm mb-2">Last updated: January 1, 2025</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Acceptance of Terms</h2>
        <p>By using Data Entry Speed Trainer, you agree to these terms. If you do not agree, please do not use the service.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Use of the Service</h2>
        <p>This tool is provided for personal, educational, and professional development purposes only. You may use this service to practice typing and data entry skills.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>No Employment Guarantee</h2>
        <p>Use of this tool does not guarantee employment. Practice completion reports generated by this app are not official certifications and may not be used as proof of professional qualification.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Data Responsibility</h2>
        <p>You are responsible for your account credentials and recovery code. We cannot recover lost passwords or data. All data is stored in your browser's localStorage and may be lost if you clear your browser data.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Disclaimer of Warranties</h2>
        <p>This service is provided "as is" without any warranty of any kind. We do not warrant that the service will be uninterrupted, error-free, or free of bugs.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, we are not liable for any damages arising from your use of this service.</p>

        <h2 style={{color:'var(--navy)',margin:'1.25rem 0 0.5rem'}}>Changes to Terms</h2>
        <p>We reserve the right to update these terms at any time. Continued use of the service constitutes acceptance of any changes.</p>

        <hr className="divider" />
        <Link to="/" className="link">← Back to Home</Link>
      </div>
    </div>
  )
}
